In [1]:
import torch

    

In [18]:

from cs336_basics.transformerStuff import softmax

exampleLogits = torch.randn(2, 5)
exampleIndices = torch.tensor([0, 2])

probs = softmax(exampleLogits, dim=-1)
probs

tensor([[0.1587, 0.0488, 0.4874, 0.2383, 0.0668],
        [0.2220, 0.1276, 0.0781, 0.2395, 0.3328]])

In [38]:
import einx
trueLogits = einx.get_at("b [v], (b [idx]) -> b 1", exampleLogits, exampleIndices)

In [32]:
eLogits = torch.exp(exampleLogits - exampleLogits.max(dim=-1, keepdim=True).values)
logSumExp = torch.log(eLogits.sum(axis=-1, keepdim=True))
logSumExp

tensor([[0.7186],
        [1.1003]])

In [44]:
torch.mean(- (trueLogits - logSumExp))

tensor(1.2175)

In [60]:
def cross_entropy(inputs, targets):
    """
        Given a tensor of inputs and targets, compute the average cross-entropy
        loss across examples.
    
        Args:
            inputs (Float[Tensor, "batch_size vocab_size"]): inputs[i][j] is the
                unnormalized logit of jth class for the ith example.
            targets (Int[Tensor, "batch_size"]): Tensor of shape (batch_size,) with the index of the correct class.
                Each value must be between 0 and `num_classes - 1`.
    
        Returns:
            Float[Tensor, ""]: The average cross-entropy loss across examples.
    """
    inputs = einx.rearrange("... v -> (...) v", inputs)
    targets = einx.rearrange("... -> (...)", targets)
    inputs = inputs - inputs.max(dim=-1, keepdim=True).values
    trueLogits = einx.get_at("b [v], (b [idx]) -> b 1", inputs, targets)
    eLogits = torch.exp(inputs)
    logSumExp = torch.log(eLogits.sum(axis=-1, keepdim=True))
    return torch.mean(- (trueLogits - logSumExp))

In [61]:
cross_entropy(exampleLogits, exampleIndices)

tensor(2.1950)

In [62]:
inputs =  torch.tensor([[0.1088, 0.1060, 0.6683, 0.5131, 0.0645],
               [0.4538, 0.6852, 0.2520, 0.3792, 0.2675],
               [0.4578, 0.3357, 0.6384, 0.0481, 0.5612],
               [0.9639, 0.8864, 0.1585, 0.3038, 0.0350],
               [0.3356, 0.9013, 0.7052, 0.8294, 0.8334],
              [0.6333, 0.4434, 0.1428, 0.5739, 0.3810],
              [0.9476, 0.5917, 0.7037, 0.2987, 0.6208],
               [0.8541, 0.1803, 0.2054, 0.4775, 0.8199]])
targets = torch.tensor([1, 0, 2, 2, 4, 1, 4, 0])
cross_entropy(inputs, targets)

tensor(1.6095)

In [65]:
inputs = torch.randn(3, 5, 7)
targets = torch.randint(0, 7, size=(3, 5))
cross_entropy(inputs, targets)

tensor(2.0685)

In [66]:
from collections.abc import Callable, Iterable
from typing import Optional
import torch
import math

In [108]:
class SGD(torch.optim.Optimizer):
    def __init__(self, params, lr=1e-3):
        if lr < 0:
            raise ValueError(f"Invalid learning rate: {lr}")
        defaults = {"lr": lr, "weight_decay" : 0.5}
        print(type(params))
        super().__init__(params, defaults)
    def step(self, closure: Optional[Callable] = None):
        loss = None if closure is None else closure()
        for group in self.param_groups:
            lr = group["lr"] # Get the learning rate.
            for p in group["params"]:
                if p.grad is None:
                    continue
                state = self.state[p] # Get state associated with p.
                t = state.get("t", 0) # Get iteration number from the state, or initial value.
                grad = p.grad.data # Get the gradient of loss with respect to p.
                p.data -= lr / math.sqrt(t + 1) * grad # Update weight tensor in-place.
                state["t"] = t + 1 # Increment iteration number.
        return loss
weights = torch.nn.Parameter(5 * torch.randn((10, 10)))
opt = SGD([weights], lr=1)
for t in range(10):
    opt.zero_grad() # Reset the gradients for all learnable parameters.
    loss = (weights**2).mean() # Compute a scalar loss value.
    print(loss.cpu().item())
    loss.backward() # Run backward pass, which computes gradients.
    opt.step() # Run optimizer step.

<class 'list'>
29.319351196289062
28.158300399780273
27.36750030517578
26.739124298095703
26.207014083862305
25.740304946899414
25.321687698364258
24.9403018951416
24.588842391967773
24.262083053588867


In [109]:
print(opt.state)

defaultdict(<class 'dict'>, {Parameter containing:
tensor([[  7.2185,  -2.4945,   0.3517,   2.3825,  -0.6931,  -1.1520,   2.5174,
          -1.7059,  -3.5319,  -5.8812],
        [  0.9454,   0.0879,  -4.3236,  12.6251,  -4.0296,  -1.3024,  -0.6779,
          -3.5746,  14.3638,   3.5311],
        [  3.1976,   8.9573,  -2.3486,   7.4501,  -2.0318,   1.1930,   0.3364,
           3.4070,  -7.0912,   5.3901],
        [ -2.4276,  -1.6256,  12.8364,  -2.2537,   3.0071,  -5.2473,  -4.8484,
           7.3746,   5.5555,   2.7918],
        [  5.7402,  -3.3578,   1.5090,   5.5736,   4.8676,  -2.5984,  -0.4501,
          -5.5459,   1.5423, -10.2543],
        [  8.4877,  -1.9380,  -2.1589,   6.4189,   0.1188,  -3.8334,  -2.8888,
           5.0671,   7.1177,  -1.9052],
        [ -6.0225,  -3.3425,   5.1899,  -4.8999,  -4.4232,  -0.2326,   2.7010,
           4.6236,   1.8738,   9.0100],
        [ -4.6705,   1.4479, -10.4200,   0.4330,  -2.1586,   3.3432,   4.7418,
           3.8059,  -1.8448, -10.1266

In [110]:
opt.param_groups[0]

{'params': [Parameter containing:
  tensor([[  7.2185,  -2.4945,   0.3517,   2.3825,  -0.6931,  -1.1520,   2.5174,
            -1.7059,  -3.5319,  -5.8812],
          [  0.9454,   0.0879,  -4.3236,  12.6251,  -4.0296,  -1.3024,  -0.6779,
            -3.5746,  14.3638,   3.5311],
          [  3.1976,   8.9573,  -2.3486,   7.4501,  -2.0318,   1.1930,   0.3364,
             3.4070,  -7.0912,   5.3901],
          [ -2.4276,  -1.6256,  12.8364,  -2.2537,   3.0071,  -5.2473,  -4.8484,
             7.3746,   5.5555,   2.7918],
          [  5.7402,  -3.3578,   1.5090,   5.5736,   4.8676,  -2.5984,  -0.4501,
            -5.5459,   1.5423, -10.2543],
          [  8.4877,  -1.9380,  -2.1589,   6.4189,   0.1188,  -3.8334,  -2.8888,
             5.0671,   7.1177,  -1.9052],
          [ -6.0225,  -3.3425,   5.1899,  -4.8999,  -4.4232,  -0.2326,   2.7010,
             4.6236,   1.8738,   9.0100],
          [ -4.6705,   1.4479, -10.4200,   0.4330,  -2.1586,   3.3432,   4.7418,
             3.8059,  -1

In [102]:
class AdamW(torch.optim.Optimizer):
    def __init__(self, params, lr=1e-3, betas = (0.9, 0.999), weight_decay = 0.01, eps = 10e-8):
        if lr < 0:
            raise ValueError(f"Invalid learning rate: {lr}")
        defaults = {"lr": lr, 
                    "beta_1" : betas[0], 
                    "beta_2" : betas[1],
                   "weight_decay" : weight_decay,
                   "epsilon" : eps}
        super().__init__(params, defaults)
    def step(self, closure: Optional[Callable] = None):
        loss = None if closure is None else closure()
        for group in self.param_groups:
            lr = group["lr"] # Get the learning rate.
            beta_1 = group['beta_1']
            beta_2 = group['beta_2']
            weight_decay = group['weight_decay']
            epsilon = group['epsilon']
            for p in group["params"]:
                if p.grad is None:
                    continue
                state = self.state[p] # Get state associated with p.
                t = state.get("t", 1)
                m = state.get("firstMoment", torch.zeros_like(p.data)) # Get iteration number from the state, or initial value.
                v = state.get("secondMoment", torch.zeros_like(p.data)) # Get iteration number from the state, or initial value.

                grad = p.grad.data # Get the gradient of loss with respect to p.
                m = beta_1 * m + (1 - beta_1) * grad
                v = beta_2 * v + (1 - beta_2) * grad ** 2
                adjustedLR = lr * ((1 - beta_2 ** t) ** 0.5) / (1 - beta_1 ** t)
                p.data -= adjustedLR * m / (v ** 0.5 + epsilon)
                p.data -= lr * weight_decay * p.data

                state['t'] = t + 1
                state['firstMoment'] = m
                state['secondMoment'] = v
                
        return loss
weights = torch.nn.Parameter(5 * torch.randn((10, 10)))
weights2 = torch.nn.Parameter(5 * torch.randn((10, 10)))

opt = AdamW([weights, weights2], lr=1)
for t in range(10):
    opt.zero_grad() # Reset the gradients for all learnable parameters.
    loss = (weights**2).mean() # Compute a scalar loss value.
    print(loss.cpu().item())
    loss.backward() # Run backward pass, which computes gradients.
    opt.step() # Run optimizer step.

26.091079711914062
19.099563598632812
13.836668968200684
10.049921035766602
7.290708065032959
5.216639995574951
3.6774072647094727
2.5980215072631836
1.8952690362930298
1.4653306007385254


In [91]:
def lrScheduler(t, alphaMax, alphaMin, Tw, Tc):
    if t < Tw:
        return t / Tw * alphaMax
    elif t <= Tc:
        cosPortion = math.cos((t - Tw) / (Tc - Tw) * math.pi)
        return alphaMin + 0.5 * (1 + cosPortion) * (alphaMax - alphaMin)
    else:
        return alphaMin

24.787813186645508
defaultdict(<class 'dict'>, {})


In [ ]:
def gradientClipper(paramList, maxNorm, eps=1e-6):
    norm = 0
    for param in paramList:
        if param.grad is None:
            continue
        norm += (param.grad.data ** 2).sum()
        
    norm = norm ** 0.5
    
    if norm < maxNorm:
        return
        
    for param in paramList:
        param.grad.data *= maxNorm / (norm + eps)